variables:
  version: 1.4.2.$(build.buildId)


trigger:
- master

pr: none


pool:
  vmImage: 'windows-latest'

steps:
- task: CmdLine@2
  inputs:
    script: 'Build.CI.cmd'
    workingDirectory: '$(Build.SourcesDirectory)\.NET\'
  displayName: 'Run Build.CI.cmd'

- task: CmdLine@2
  inputs:
    script: 'CreateAllPackages.cmd'
    workingDirectory: '$(Build.SourcesDirectory)\.NET\'
  displayName: 'Run CreateAllPackages.cmd'
  

- task: NuGetCommand@2
  displayName: 'push nuget'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.SourcesDirectory)\.NET\nuget\*.nupkg;!$(Build.SourcesDirectory)\.NET\nuget\*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'nuget-curiosity'
